import type { ConsolePayload } from './types';

export const mockConsoleData: ConsolePayload = {
  status: {
    adapters: 2,
    plugins: 3,
    jobs: 4,
    schedules: 2,
  },
  adapters: [
    {
      id: 'adapter-onebot-demo',
      adapter: 'onebot',
      source: 'onebot',
      status: 'registered',
      health: 'ready',
      online: true,
      statusSource: 'mock-adapter-state',
      configSource: 'mock-bootstrap',
      statePersisted: true,
      updatedAt: '2026-04-02T09:10:00Z',
      summary: 'registered adapter lifecycle facts for the local mock preview',
    },
    {
      id: 'adapter-webhook-demo',
      adapter: 'webhook',
      source: 'webhook',
      status: 'registered',
      health: 'degraded',
      online: false,
      statusSource: 'mock-adapter-state',
      configSource: 'mock-bootstrap',
      statePersisted: true,
      updatedAt: '2026-04-02T09:12:00Z',
      summary: 'registered but currently offline in the local mock preview',
    },
  ],
  plugins: [
    {
      id: 'plugin-echo',
      name: 'Echo Plugin',
      version: '0.1.0',
      apiVersion: 'v0',
      mode: 'inproc',
      permissions: ['reply:write'],
      configSchema: {
        type: 'object',
        properties: {
          prefix: {
            type: 'string',
          },
        },
      },
      entry: {
        module: 'plugins/plugin-echo/plugin',
        symbol: 'New',
      },
    },
    {
      id: 'plugin-scheduler',
      name: 'Scheduler Plugin',
      version: '0.1.0',
      apiVersion: 'v0',
      mode: 'subprocess',
      permissions: ['schedule:read', 'schedule:trigger'],
      configSchema: {
        type: 'object',
      },
      entry: {
        binary: 'plugins/plugin-scheduler/bin/plugin-scheduler',
      },
    },
    {
      id: 'plugin-admin',
      name: 'Admin Plugin',
      version: '0.1.0',
      apiVersion: 'v0',
      mode: 'subprocess',
      permissions: ['plugin:inspect', 'queue:inspect', 'logs:read'],
      configSchema: {
        type: 'object',
      },
      entry: {
        binary: 'plugins/plugin-admin/bin/plugin-admin',
      },
    },
  ],
  jobs: [
    {
      id: 'job-echo-001',
      type: 'reply.dispatch',
      status: 'done',
      payload: {
        eventId: 'evt-001',
      },
      retryCount: 0,
      maxRetries: 1,
      timeout: 5_000_000_000,
      lastError: '',
      createdAt: '2026-04-02T09:10:00Z',
      startedAt: '2026-04-02T09:10:01Z',
      finishedAt: '2026-04-02T09:10:02Z',
      nextRunAt: null,
      deadLetter: false,
      correlation: 'corr-evt-001',
    },
    {
      id: 'job-ai-014',
      type: 'ai.chat',
      status: 'retrying',
      payload: {
        sessionId: 'sess-14',
      },
      retryCount: 1,
      maxRetries: 3,
      timeout: 30_000_000_000,
      lastError: 'upstream timeout',
      createdAt: '2026-04-02T09:11:00Z',
      startedAt: '2026-04-02T09:11:05Z',
      finishedAt: null,
      nextRunAt: '2026-04-02T09:11:45Z',
      deadLetter: false,
      correlation: 'corr-ai-014',
    },
    {
      id: 'job-sync-201',
      type: 'adapter.reconnect',
      status: 'running',
      payload: {
        adapter: 'onebot',
      },
      retryCount: 0,
      maxRetries: 5,
      timeout: 10_000_000_000,
      lastError: '',
      createdAt: '2026-04-02T09:12:00Z',
      startedAt: '2026-04-02T09:12:02Z',
      finishedAt: null,
      nextRunAt: null,
      deadLetter: false,
      correlation: 'corr-adapter-201',
    },
    {
      id: 'job-batch-404',
      type: 'workflow.resume',
      status: 'dead',
      payload: {
        workflowId: 'wf-404',
      },
      retryCount: 3,
      maxRetries: 3,
      timeout: 20_000_000_000,
      lastError: 'state snapshot missing',
      createdAt: '2026-04-02T09:13:00Z',
      startedAt: '2026-04-02T09:13:04Z',
      finishedAt: '2026-04-02T09:13:30Z',
      nextRunAt: null,
      deadLetter: true,
      correlation: 'corr-workflow-404',
    },
  ],
  schedules: [
    {
      id: 'schedule-delay-001',
      kind: 'delay',
      source: 'runtime-demo-scheduler',
      eventType: 'message.received',
      cronExpr: '',
      delayMs: 30000,
      executeAt: null,
      dueAt: '2026-04-02T09:11:45Z',
      createdAt: '2026-04-02T09:11:15Z',
      updatedAt: '2026-04-02T09:11:15Z',
    },
    {
      id: 'schedule-cron-014',
      kind: 'cron',
      source: 'plugin-scheduler',
      eventType: 'schedule.triggered',
      cronExpr: '0 * * * *',
      delayMs: 0,
      executeAt: null,
      dueAt: '2026-04-02T10:00:00Z',
      createdAt: '2026-04-02T09:00:00Z',
      updatedAt: '2026-04-02T09:30:00Z',
    },
  ],
  logs: [
    '2026-04-02T09:10:00Z INFO trace_id=trace-001 event_id=evt-001 plugin_id=plugin-echo dispatch started',
    '2026-04-02T09:10:02Z INFO trace_id=trace-001 event_id=evt-001 plugin_id=plugin-echo reply sent',
    '2026-04-02T09:11:10Z WARN trace_id=trace-014 run_id=job-ai-014 plugin_id=plugin-ai-chat upstream timeout, retry scheduled',
    '2026-04-02T09:12:02Z INFO trace_id=trace-201 correlation_id=corr-adapter-201 adapter_id=onebot reconnect job running',
    '2026-04-02T09:13:30Z ERROR trace_id=trace-404 run_id=job-batch-404 plugin_id=plugin-workflow-demo dead letter after missing state snapshot',
  ],
  config: {
    Runtime: {
      Environment: 'development',
      LogLevel: 'debug',
      HTTPPort: 8080,
    },
  },
  meta: {
    runtime_entry: 'apps/runtime',
    demo_paths: ['/demo/onebot/message', '/demo/ai/message', '/demo/schedules/echo-delay'],
    sqlite_path: 'data/dev/runtime.sqlite',
    scheduler_interval_ms: 100,
    ai_worker_enabled: true,
    console_mode: 'read-only',
  },
  observability: {
    jobDispatchReady: 1,
    scheduleDueReady: 0,
    jobStateSource: 'mock-jobs',
    scheduleStateSource: 'mock-schedules',
    logStateSource: 'mock-logs',
    traceStateSource: 'mock-traces',
    metricsStateSource: 'mock-metrics',
    verificationEndpoints: ['GET /api/console'],
    summary: 'mock console payload for local read-only preview only',
  },
};
